spring:
  application:
    name: PhotoAppApiConfigServer

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: {github.uri}
          username: {github.username}
          password: {github.password}
          cloneOnStart: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8012

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh