spring:
  application:
    name: PhotoAppApiConfigServer

  cloud:
    config:
      server:
        git:
          uri:
          username:
          password:
          cloneOnStart: true

server:
  port: 8012