spring:
  devtools:
    restart:
      enabled: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1

logging:
  level:
    com:
      alexcode:
        photoapp:
          api:
            users:
              PhotoAppApiUsers:
                feign:
                  AlbumServiceClient: DEBUG

feign:
  hystrix:
    enabled: true

