server:
  port: 8011

api:
  login:
    path: /users-ws/users/login
  registration:
    path: /users-ws/users
  h2console:
    path: /users-ws/h2-console/**
  zuul:
    actuator:
      path: /actuator/*
  users:
    actuator:
      path: /users-ws/actuator/*

spring:
  application:
    name: zuul

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

ribbon:
  ReadTimeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - beans
          - health
          - routes
          - httptrace
