server:
  port: 8011

api:
  login:
    path: /users-ws/users/login
  registration:
    path: /users-ws/users
  h2console:
    path: /users-ws/h2-console/**

spring:
  application:
    name: zuul

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

ribbon:
  ReadTimeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

jwt:
  secretKey: fh279rfhf0923yrfwhfk2fh8923hjfkfheowf8123gfhidjfnv384jvaodfeb83gvbu42r93jbknl
  authorizationHeader: Authorization
  tokenPrefix: Bearer
  tokenExpirationDays: 7