server:
  port: ${PORT:0}

spring:
  application:
    name: albums-ws

  devtools:
    restart:
      enabled: true

  jackson:
    property-naming-strategy: SNAKE_CASE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
